### ISSUE TITLE
Latest repair_settings.php does not work with SMF 2.0.13

### ISSUE THREAD

**Issue by Rupurudu** [SimpleMachines/tools#27]
#17 works fine. 
#18 shows up this error:	
`Notice: Undefined variable: array_settings in D:\IIS Siteleri\UHKC Forum\repair_settings.php on line 697`
#25 shows up this error plus 2 more:
`Notice: Undefined variable: array_settings in D:\IIS Siteleri\UHKC Forum\repair_settings.php on line 755`
`Tasks Directory: Value not found!`
`Packages Directory: Value not found!`

**Comment by illori** [comment]
since those are not part of SMF 2.0, we need a way to make sure repair_settings.php does not try to set them for SMF 2.0 and just for SMF 2.1.

@jdarwood007 can you look into this?

**Comment by jdarwood007** [comment]
The latest commit should clear those up.

**Comment by illori** [comment]
it does not look like you made that into a PR here, did you mean to do that?

**Comment by jdarwood007** [comment]
I keep forgetting to fix it but my connection to the tools repo is using here as origin and I keep pushing to it.

**Comment by jdarwood007** [comment]
Actually, looks like I did fix it and forgot.  Fixed
