### ISSUE TITLE
Repair Settings, user feedback

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/tools#65]
Changing the label (wording) on the "Restore all settings" button to "Apply all recommendations" would certainly be helpful for a first time user of repair_settings in addition to more accurately describing what pressing that button does. 

https://www.simplemachines.org/community/index.php?msg=4148715

**Comment by nc3man** [comment]
If someone takes on this update, a setting which is missed by repair_settings.php is smf_themes: header_logo_url, although it can be set in Theme Options. Not sure everyone would know to look there, or if there are other changes beyond this they may miss. Even if you don't take the time to add every single thing like this to repair_settings.php, perhaps a list of items that can be set in the SMF Admin section could be listed on the screen after the Save.

**Comment by DiegoAndresCortes** [comment]
That's a theme option, it's not a main setting

**Comment by LexArma** [comment]
> Even if you don't take the time to add every single thing like this to repair_settings.php, perhaps a list of items that should be checked in the SMF Admin section could be listed on the screen after the Save.

Listing things outside of the tools intended scope would easily be a never ending task that would add a lot to the maintenance needs of the tool itself. Remember that the tool is only designed to fix everything you might need to fix in order to gain access to the admin control panel, where you can then continue with SMF's built in configuration tools and take care of the rest.  Documentation in the wiki might be a better place for things like additional settings to consider after a domain change.

**Comment by nc3man** [comment]
Fully agree with your comment. No point in wasting precious resources on a tool only a few may use anyway. I wasn't even aware of the wiki page for this tool and it would have been useful to read it before first use as I was just guessing what was going on. The documentation is quite good and I think adding a list of other things to do in the Admin backend after running repair_settings would be useful. I just stumbled upon the unmodified header_logo_url by searching the database. That setting is buried a few levels down in Theme Options, so a pointer to things like that might be great to add to the wiki page. Btw, would it be appropriate to display at the top of the repair_settings windows the link to the wiki page and a recommendation for first time or infrequent users to read it? I only bumbled upon that as a link to the tool was suggested in a SMF forum reply. In fact, I only knew of the existence of repair_settings by reading a few posts by others on your community forum.

**Comment by nc3man** [comment]
I executed a pull request PR #66 with my one-line change in my forked tools repository. Not sure how it gets linked to the issue.

**Comment by LexArma** [comment]
The relevant Wiki article would be https://wiki.simplemachines.org/smf/Repair_settings.php
The different configuration options within 2.1 can be found through https://wiki.simplemachines.org/smf/Category:As_an_administrator_2.1

I requested a review for your pull request, thank you for your interest in improving SMF! :)
