### ISSUE TITLE
repair_settings.php error for 1.1.x (non-critical)

### ISSUE THREAD

**Issue by CoreISP** [SimpleMachines/tools#7]
Repair_settings.php on SMF 1.1.x is broken for the attachment dir.
It looks like repair_settings.php is trying to execute the wrong query on SMF 1.1.x and is actually trying to execute SMF 2.0.x code.

Error: 
Warning: mysql_num_rows() expects parameter 1 to be resource, boolean given in repair_settings.php on line 674

Apparently, the query that is being ran is: (Courtesy of Labradoodle-360) 
SELECT DISTINCT(id_folder), id_attach FROM {db_prefix}attachments

Which returns an error, and results in a bool(false)

The id_folder is not present, iirc, in SMF 1.1.x because it does not support multiple folders...
If I understood correctly from Lab, repair_settings is supposed to execute this for 1.1.x:
'select_tables' => $context['is_legacy'] ? ($id . ' as id_folder, ID_ATTACH as id_attach') : 'DISTINCT(id_folder), id_attach',

For some reason, this is not working correctly.
It is non-critical though, it still correctly reads the attachments directory that is currently in use, and does make the correct suggestion what it should change it to.
However, it just looks a bit sloppy. =) 

-edit-
Not sure if relevant, but this happened during execution on a... on a... a... SMF 1.1.9 installation. o0

Greetz,
- Liroy

**Comment by jdarwood007** [comment]
Since it seems resolved, @CoreISP hasn't responded with any feedback and nobody is able to confirm or deny this.  I will close it.  Can reopen if we need to.
