### ISSUE TITLE
new avatars folder

### ISSUE THREAD

**Issue by illori** [SimpleMachines/tools#9]
in 2.1 the avatars folder is separate from the packages folder, we need an easy way to reset this path.

**Comment by jdarwood007** [comment]
Avatars are in the repair_settings.php from what I see.  Unless this is something different?

**Comment by illori** [comment]
the custom avatars folder needs to be added, not just the one for the gallery of avatars. in SMF 2.1 by default the user uploaded avatars are not in the attachments folder by default.

**Comment by jdarwood007** [comment]
That was fixed by PR #17

**Comment by illori** [comment]
then i guess this can be closed.
